name: ALENN_Default_Environment
channels:
  - defaults
dependencies:
  - ipywidgets=7.5.1
  - joblib=0.16.0
  - notebook=6.1.1
  - numpy=1.19.1
  - matplotlib=3.3.1
  - pandas=1.1.1
  - python=3.7.9
  - tqdm=4.50.0
  - scipy=1.5.2
  - seaborn=0.11.0
  - setuptools=49.6.0
  - wheel=0.35.1
  - pip:
    - keras==2.2.4
    - tensorflow==1.15.0

